(module
 (type $i (func (result i32)))
 (type $v (func))
 (import "env" "abort" (func $~lib/env/abort))
 (global $~lib/allocator/arena/startOffset (mut i32) (i32.const 0))
 (global $~lib/allocator/arena/offset (mut i32) (i32.const 0))
 (global $abi/condition (mut i32) (i32.const 0))
 (global $abi/y (mut i32) (i32.const 0))
 (memory $0 0)
 (export "memory" (memory $0))
 (export "exported" (func $abi/exported))
 (export "exportedExported" (func $abi/exportedExported))
 (export "exportedInternal" (func $abi/exportedInternal))
 (start $start)
 (func $abi/exported (; 1 ;) (type $i) (result i32)
  (i32.const -128)
 )
 (func $abi/exportedExported (; 2 ;) (type $i) (result i32)
  (call $abi/exported)
 )
 (func $abi/internal (; 3 ;) (type $i) (result i32)
  (i32.const 128)
 )
 (func $abi/exportedInternal (; 4 ;) (type $i) (result i32)
  (i32.shr_s
   (i32.shl
    (call $abi/internal)
    (i32.const 24)
   )
   (i32.const 24)
  )
 )
 (func $start (; 5 ;) (type $v)
  (set_global $~lib/allocator/arena/startOffset
   (i32.const 8)
  )
  (set_global $~lib/allocator/arena/offset
   (get_global $~lib/allocator/arena/startOffset)
  )
  (drop
   (call $abi/internal)
  )
  (set_global $abi/condition
   (i32.const 1)
  )
  (set_global $abi/y
   (i32.const 0)
  )
  (if
   (get_global $abi/y)
   (block
    (call $~lib/env/abort)
    (unreachable)
   )
  )
 )
)
